# Generated by Django 5.1.5 on 2025-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_text_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I have nothig to say)', max_length=1000),
            preserve_default=False,
        ),
    ]
