# Generated by Django 5.1.4 on 2025-01-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_match_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additionalPhotos',
        ),
    ]
