# Generated by Django 5.1.4 on 2025-01-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_additionalphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additionalPhotos',
        ),
    ]
