# Generated by Django 5.1.4 on 2025-01-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_profile_additionalphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
