# Generated by Django 5.1.5 on 2025-01-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_photos',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='additional_photos'),
        ),
    ]
