# Generated by Django 5.1.5 on 2025-01-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_additional_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='additional_photos',
        ),
    ]
