# Generated by Django 5.1.5 on 2025-01-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_message_options_remove_message_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
