# Generated by Django 5.1.5 on 2025-01-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_message_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
