apiVersion: v1
kind: Service
metadata:
  name: busy-dating
spec:
  type: NodePort
  selector:
    app: busy-dating
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30000
